# Generated by Django 4.2 on 2025-02-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('disponible', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en_oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('dirección', models.CharField(max_length=200)),
                ('estatus', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]

# Generated by Django X.Y on YYYY-MM-DD HH:MM

# from django.db import migrations, models
# import django.db.models.deletion

# class Migration(migrations.Migration):

#     dependencies = [
#         ('auth', '0012_auto_20210423_1234'),
#         ('website', '0001_initial'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='orden',
#             name='user',
#             field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='auth.user'),
#         ),
#     ]

# from django.contrib.auth.models import User
# from django.db import models

# class Orden(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='ordenes')
#     nombre = models.CharField(max_length=200)
#     email = models.EmailField()
#     telefono = models.CharField(max_length=20)
#     sesion_id = models.CharField(max_length=100, null=True, blank=True)
#     total = models.DecimalField(max_digits=10, decimal_places=0)
#     metodo_pago = models.CharField(max_length=20, choices=[('nequi', 'Nequi'), ('bancolombia', 'Bancolombia')])
#     pagado = models.BooleanField(default=False)
#     fecha_creacion = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"Orden #{self.id} - {self.nombre}"