# Generated by Django 5.1.6 on 2025-03-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_images/placeholder-user-profile.png', upload_to='profile_images/'),
        ),
    ]
