# Generated by Django 5.1.6 on 2025-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_carritoitem_imagen_orden_ordenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
