# Generated by Django 5.1.6 on 2025-03-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_orden_usuario_orden_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='user',
            new_name='usuario',
        ),
    ]
